CREATE OR REPLACE PROCEDURE LIS_ZO.InsertTESTRESULTS(
    P_ID LIS_ZO.TESTRESULTS.ID%TYPE
   ,P_SAMPLENO LIS_ZO.TESTRESULTS.SAMPLENO%TYPE
   ,P_HISTESTCODE LIS_ZO.TESTRESULTS.HISTESTCODE%TYPE
   ,P_LISTESTCODE LIS_ZO.TESTRESULTS.LISTESTCODE%TYPE
   ,P_SPECIMENNAME LIS_ZO.TESTRESULTS.SPECIMENNAME%TYPE
   ,P_RESULTDATE LIS_ZO.TESTRESULTS.RESULTDATE%TYPE
   ,P_SAMPLECOLLECTIONDATE LIS_ZO.TESTRESULTS.SAMPLECOLLECTIONDATE%TYPE
   ,P_SAMPLERECEIVEDDATE LIS_ZO.TESTRESULTS.SAMPLERECEIVEDDATE%TYPE
   ,P_AUTHORIZATIONDATE LIS_ZO.TESTRESULTS.AUTHORIZATIONDATE%TYPE
   ,P_AUTHORIZEDBY LIS_ZO.TESTRESULTS.AUTHORIZEDBY%TYPE
   ,P_REVIEWDATE LIS_ZO.TESTRESULTS.REVIEWDATE%TYPE
   ,P_REVIEWEDBY LIS_ZO.TESTRESULTS.REVIEWEDBY%TYPE
   ,P_TECHNICIANNOTE LIS_ZO.TESTRESULTS.TECHNICIANNOTE%TYPE
   ,P_DOCTORNOTE LIS_ZO.TESTRESULTS.DOCTORNOTE%TYPE
   ,P_CREATEDBY LIS_ZO.TESTRESULTS.CREATEDBY%TYPE
   ,P_CREATEDON LIS_ZO.TESTRESULTS.CREATEDON%TYPE
   ,P_PATIENTID LIS_ZO.TESTRESULTS.PATIENTID%TYPE
   ,P_TESTREQUESTID LIS_ZO.TESTRESULTS.TESTREQUESTID%TYPE
   ,P_EQUIPMENTID LIS_ZO.TESTRESULTS.EQUIPMENTID%TYPE)
IS
BEGIN

  INSERT INTO  LIS_ZO.TESTRESULTS
           (ID
           , SAMPLENO
           , HISTESTCODE
           , LISTESTCODE
           , SPECIMENNAME
           , RESULTDATE
           , SAMPLECOLLECTIONDATE
           , SAMPLERECEIVEDDATE
           , AUTHORIZATIONDATE
           , AUTHORIZEDBY
           , REVIEWDATE
           , REVIEWEDBY
           , TECHNICIANNOTE
           , DOCTORNOTE
           , CREATEDBY
           , CREATEDON
           , PATIENTID
           , TESTREQUESTID
           , EQUIPMENTID)
      VALUES
           (
	    P_ID
           ,P_SAMPLENO
           ,P_HISTESTCODE
           ,P_LISTESTCODE
           ,P_SPECIMENNAME
           ,P_RESULTDATE
           ,P_SAMPLECOLLECTIONDATE
           ,P_SAMPLERECEIVEDDATE
           ,P_AUTHORIZATIONDATE
           ,P_AUTHORIZEDBY
           ,P_REVIEWDATE
           ,P_REVIEWEDBY
           ,P_TECHNICIANNOTE
           ,P_DOCTORNOTE
           ,P_CREATEDBY
           ,P_CREATEDON
           ,P_PATIENTID
           ,P_TESTREQUESTID
           ,P_EQUIPMENTID
		   );

END;
/
