CREATE OR REPLACE PROCEDURE LIS_ZO.InsertTESTRESULTDETAILS (
    P_ID            LIS_ZO.TESTRESULTDETAILS.ID%type
   ,P_LISPARAMCODE  LIS_ZO.TESTRESULTDETAILS.LISPARAMCODE%type
   ,P_LISPARAMVALUE LIS_ZO.TESTRESULTDETAILS.LISPARAMVALUE%type
   ,P_LISPARAMUNIT  LIS_ZO.TESTRESULTDETAILS.LISPARAMUNIT%type
   ,P_CREATEDBY     LIS_ZO.TESTRESULTDETAILS.CREATEDBY%type
   ,P_CREATEDON     LIS_ZO.TESTRESULTDETAILS.CREATEDON%type
   ,P_TESTRESULTID  LIS_ZO.TESTRESULTDETAILS.TESTRESULTID%type)
IS
BEGIN
INSERT INTO LIS_ZO.TESTRESULTDETAILS
(ID ,LISPARAMCODE,LISPARAMVALUE, LISPARAMUNIT, CREATEDBY,CREATEDON ,TESTRESULTID)
Values (P_ID,P_LISPARAMCODE,P_LISPARAMVALUE,P_LISPARAMUNIT,P_CREATEDBY,P_CREATEDON,P_TESTRESULTID);
COMMIT;
END;
/
